// Ambient module declaration so TypeScript accepts the `.css` import in
// App.tsx (`import './src/global.css'`) — Uniwind's Metro plugin handles the
// actual resolution/transform at bundle time; this only satisfies `tsc`.
//
// Kept in its own file rather than in `uniwind-types.d.ts` because that file
// is regenerated by Uniwind's Metro plugin on `expo start` / `expo export`
// (see its own header comment) and would silently drop a hand-added
// declaration on the next regeneration.
declare module '*.css';
